networks:
  expense:
    driver: bridge
volumes:
    mysql:
services:
  mysql:
    image: acavinash/mysql:v1
    container_name: mysql
    networks:
      - expense
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: acavinash/backend:v1
    container_name: backend
    networks:
      - expense
    depends_on:
      - mysql
  frontend:
    image: acavinash/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - expense
    depends_on:
      - backend